// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1:string,arg2:string):void;

export function SendMessage(arg1:string):void;

export function SendPassword(arg1:string):void;
