// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1, arg2) {
  window['go']['main']['App']['CreateConnection'](arg1, arg2);
}

export function SendMessage(arg1) {
  window['go']['main']['App']['SendMessage'](arg1);
}

export function SendPassword(arg1) {
  window['go']['main']['App']['SendPassword'](arg1);
}
